#  Copyright 2022 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---

- name: Initialize beegfs_connauth_status
  ansible.builtin.set_fact:
    beegfs_connauth_status: false

- name: Validate beegfs_mgmt_server inputs
  when: beegfs_mgmt_server | length > 1
  block:
    - name: Test reachability of beegfs_mgmt_server
      ansible.builtin.command: ping -c3 {{ beegfs_mgmt_server }}
      changed_when: false
      failed_when: false
      register: beegfs_mgmt_server_reachablility

    - name: Verify beegfs_mgmt_server reachable or not
      ansible.builtin.fail:
        msg: "{{ beegfs_mgmt_server_not_reachable_msg }}"
      when: ping_msg in beegfs_mgmt_server_reachablility.stdout

- name: Validate beegfs_client_version
  ansible.builtin.assert:
    that:
      - beegfs_client_version >= '7.2'
    success_msg: "{{ beegfs_client_version_success_msg }}"
    fail_msg: "{{ beegfs_client_version_fail_msg }}"

- name: Validate shared secret file for beegfs version >= 7.2.7
  when: beegfs_client_version >= '7.2.7'
  block:
    - name: Validate the shared secret file
      ansible.builtin.stat:
        path: "{{ beegfs_secret_storage_filepath }}"
      register: file_result

    - name: Validate the shared secret file existence
      ansible.builtin.pause:
        seconds: "{{ warning_wait_time }}"
        prompt: "{{ beegfs_shared_secret_failure_msg }}"
      when: not file_result.stat.exists

    - name: Set beegfs_connauth_status
      ansible.builtin.set_fact:
        beegfs_connauth_status: true
      when: file_result.stat.exists

- name: Assert beegfs_unmount_client when beegfs_version_change
  ansible.builtin.assert:
    that:
      - beegfs_unmount_client == true
    success_msg: "{{ unmount_success_msg }}"
    fail_msg: "{{ unmount_failure_msg }}"
  when: beegfs_version_change

- name: Check for compatability of BeeGFs version
  ansible.builtin.fail:
    msg: "{{ compatability_msg }}"
  when:
    - beegfs_client_version == latest_version
    - beegfs_version_change
