#  Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---

- name: Label nodes with Gaudi
  kubernetes.core.k8s:
    kind: Node
    name: "{{ item }}"
    definition:
      metadata:
        labels:
          "{{ node_label_for_habana_device_plugin }}": "true"
  when:
    - hostvars['localhost']['is_gaudi_cluster'] is defined
    - hostvars[item]['node_has_gaudi'] | default(false)
  loop: "{{ groups['kube_node'] | default([]) }}"

# HABANA PLUGIN
- name: Deploy Habana Device plugin
  when:
    - "'habanalabs-device-plugin-daemonset' not in k8s_daemonset.stdout"
    - k8s_version >= minimal_gaudi_k8s_version
    - hostvars['localhost']['is_gaudi_cluster'] is defined
  block:
    - name: Download habana-device-plugin yaml file
      ansible.builtin.uri:
        url: "{{ habana_device_plugin_yaml_url }}"
        return_content: true
      register: habana_device_plugin_yaml_content

    - name: Modify habana-device-plugin yaml file
      ansible.builtin.set_fact:
        with_node_selector: |
          {{ habana_device_plugin_yaml_content.content }}
                nodeSelector:
                  {{ node_label_for_habana_device_plugin }}: 'true'

    - name: Install habana-device-plugin
      ansible.builtin.shell: |
        set -o pipefail
        echo "{{ with_node_selector }}" | kubectl create -f -
      changed_when: true
      args:
        executable: /bin/bash

    - name: Include pod status
      ansible.builtin.include_tasks: pod_status.yml
      vars:
        track_module_name: "habanalabs-device-plugin"
