# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---
# ***********************************************************************
# DO NOT REMOVE OR COMMENT OUT ANY LINES IN THIS FILE.
# SIMPLY APPEND THE REQUIRD VALUES AGAINST THE PARAMETER OF YOUR CHOICE.
# ***********************************************************************
# By default, set to false to enable secure (HTTP) connection to the Pulp server.
# Update to true if required to connect to the Pulp server using HTTPS.
pulp_protocol_https: false

# enable_routed_internet should be set to true for clusters having partial or no dedicated internet access.
# enable_routed_internet should be set to false for clusters having dedicated internet access.
# When set to true, Squid Proxy will be deployed on OIM and will be used for routing requests from compute nodes.
# By default, enable_routed_internet is set to true.
enable_routed_internet: true

# Optional
# This variable accepts the repository urls of the user which contains the packages required for the cluster.
# User should make sure required disk space is available.
# This variable accepts repo url, gpgkey and name, sslcacert, sslclientkey, and sslclientcert, policy
# url: defines the baseurl for the repository
# gpgkey: defines gpgkey for the repository
# name: defines name for the repository
# sslcacert, sslclientkey, sslclientcert : Defines respective certificate file paths.
# policy: Add the policy(always, partial, never) depending upon desired configuration.
# If gpgkey is empty then gpgcheck will be disabled for that repository
# This variable should not have jinja variables in it.
# and user leaves the gpgkey field empty (gpgkey: "" ), omnia configures the repository as a trusted source and the user is solely
# responsible in maintaining the security.
# If you are using SSL certificates for encryption, include the sslcacert, sslclientkey, and sslclientcert fields.
# Example:
# - { url: "", gpgkey: "", name: "", sslcacert: "", sslclientkey: "", sslclientcert: "", policy: "" }
# Omit these fields entirely if SSL is not in use.
# Example:
# user_repo_url:
#   - {url: "",gpgkey: "",name: ""}
user_repo_url:

# Optional
# This variable accepts the registry url along with port of the user which contains the images required for cluster.
# User should make sure required disk space is available.
# This variable accepts host and cert_path
# host: defines the url and port for registry
# cert_path: defines the absolute path of the certificates for each registry.
# key_path: defines the key certificate path for user registry
# If cert_path is empty, insecure registry will be configured.
# Example:
# user_registry:
#   - { host: 10.11.0.100, cert_path: "/home/ca.crt", key_path: "" }
#   - { host: registryhostname.registry.test, cert_path: "", key_path: "" }
user_registry:

# Mandatory when cluster_os_type is rhel in softwares_config.json
# User has to provide the code ready builder url that should not have a RedHat subscription authentication inorder to download the packages
# and the rhel_os_url configured via proxy in compute nodes
# Example:
# rhel_os_url:
#   - {url: "http://crb.com/CRB/x86_64/os/", gpgkey: "http://crb.com/CRB/x86_64/os/RPM-GPG-KEY", name: "codeready-builder"}
rhel_os_url:
  - {url: "", gpgkey: "", name: ""}

### ADVANCE CONFIGURATIONS FOR LOCAL REPO ###
# Mandatory
# This variable defines all the repo urls from where rpms will be downloaded for omnia features when cluster_os_type is rhel.
# Making incorrect changes to this variable can cause omnia failure. Please edit cautiously.
# 'url' defines the baseurl for the repository
# 'gpgkey' defines gpgkey for the repository
# If 'gpgkey' is kept empty then gpgcheck=0 for that repository
omnia_repo_url_rhel:
  - { url: "https://download.docker.com/linux/centos/9/x86_64/stable", gpgkey: "https://download.docker.com/linux/centos/gpg", name: "docker-ce-repo"}
  - { url: "https://repo.radeon.com/rocm/rhel9/{{ rocm_version }}/main", gpgkey: "https://repo.radeon.com/rocm/rocm.gpg.key", name: "rocm"}
  - { url: "https://dl.fedoraproject.org/pub/epel/9/Everything/x86_64/", gpgkey: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9", name: "epel"}
  - { url: "https://repo.radeon.com/amdgpu/{{ amdgpu_version }}/rhel/{{ cluster_os_version }}/main/x86_64", gpgkey: "https://repo.radeon.com/rocm/rocm.gpg.key", name: "amdgpu"}
  - { url: "https://www.beegfs.io/release/beegfs_{{beegfs_version}}/dists/rhel9", gpgkey: "https://www.beegfs.io/release/beegfs_{{beegfs_version}}/gpg/GPG-KEY-beegfs", name: "beegfs"}
  - { url: "https://yum.repos.intel.com/oneapi", gpgkey: "https://yum.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB", name: "oneapi"}
  - { url: "https://ltb-project.org/rpm/openldap26/9/x86_64", gpgkey: "", name: "ldap"}
  - { url: "https://nvidia.github.io/libnvidia-container/stable/rpm/x86_64", gpgkey: "https://nvidia.github.io/libnvidia-container/gpgkey", name: "nvidia-repo"}
  - { url: "https://a2o.github.io/snoopy-packages/repo/centos/9/stable/", gpgkey: "", name: "snoopy"}
  - { url: "https://xcat.org/files/xcat/repos/yum/2.17/xcat-core", gpgkey: "http://xcat.org/files/xcat/repos/yum/2.17/xcat-core/repodata/repomd.xml.key", name: "xcat-core"}
  - { url: "https://xcat.org/files/xcat/repos/yum/2.17/xcat-dep/rh9/x86_64", gpgkey: "http://xcat.org/files/xcat/repos/yum/xcat-dep/rh9/x86_64/repodata/repomd.xml.key", name: "xcat-dep"}
