# Copyright 2022 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: Validate BMC group data file exists
  ansible.builtin.stat:
    path: "{{ bmc_group_data_filename }}"
  register: bmc_group_data_stat

- name: Fail if BMC group data file does not exist
  ansible.builtin.fail:
    msg: "{{ bmc_group_data_file_not_found_msg }}"
  when: not bmc_group_data_stat.stat.exists

- name: Read BMC group data
  ansible.builtin.set_fact:
    bmc_group_data: "{{ lookup('file', bmc_group_data_filename).splitlines() }}"

- name: Validate BMC group data headers
  ansible.builtin.fail:
    msg: "{{ bmc_group_data_invalid_msg }}'"
  when: bmc_group_data[0] != bmc_group_data_headers

- name: Extract BMC_IP values
  ansible.builtin.set_fact:
    bmc_ips: "{{ bmc_group_data[1:] | map('split', ',') | map('first') | list }}"

- name: Validate each BMC IP
  ansible.builtin.fail:
    msg: "{{ bmc_group_data_invalid_ip_msg }} : {{ item }}"
  when: item is not match('^\\d{1,3}(\\.\\d{1,3}){3}$')
  loop: "{{ bmc_ips }}"

- name: Validate BMC reachability
  update_bmc_group_entry:
    csv_path: "{{ bmc_group_csv_path }}"
    bmc_username: "{{ bmc_username }}"
    bmc_password: "{{ bmc_password }}"
    verify_bmc: true
  register: bmc_result

- name: Show verified BMC entries
  when: bmc_result.verified_bmc | length > 0
  ansible.builtin.debug:
    msg: "BMC entries valid for IPs: {{ bmc_result.verified_bmc | join(', ') }}."

- name: Show Redfish Disabled Warning
  when: bmc_result.redfish_disabled | length > 0
  ansible.builtin.debug:
    msg: "{{ redfish_disabled_msg | replace('\n', ' ') }}"

- name: Show Invalid BMC Credentials
  when: bmc_result.invalid_creds | length > 0
  ansible.builtin.debug:
    msg: "{{ invalid_creds_msg | replace('\n', ' ') }}"

- name: Show Unreachable BMC IPs
  when: bmc_result.unreachable_bmc | length > 0
  ansible.builtin.debug:
    msg: "{{ unreachable_bmc_msg | replace('\n', ' ') }}"

- name: Warning for user to fix BMC issues
  when: >
    (bmc_result.redfish_disabled | length > 0) or
    (bmc_result.invalid_creds | length > 0) or
    (bmc_result.unreachable_bmc | length > 0)
  ansible.builtin.fail:
    msg: "{{ invalid_bmc_fail_msg | replace('\n', ' ') }}"
