#  Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---

- name: Get all discovered OIM HA and service nodes from DB
  community.postgresql.postgresql_query:
    db: omniadb
    login_user: postgres
    query: |
      SELECT node,bmc_ip
      FROM cluster.nodeinfo
      WHERE role IN ('service_node', 'oim_ha_node') AND (status IS NOT NULL AND status = 'booted');
    login_password: "{{ postgresdb_password }}"
  become: true
  become_user: postgres
  register: helper_node_info
  failed_when: false
  no_log: true
  delegate_to: omnia_provision
  connection: ssh

- name: Check if any helper nodes were found
  ansible.builtin.debug:
    msg: "{{ helper_nodes_DB_status }}"
  when:
    - helper_node_info.query_result is defined
    - helper_node_info.query_result | length > 0

- name: Disable the boot option on the OIM HA and service nodes
  ansible.builtin.include_tasks: disable_helper_node_boot.yml
  loop: "{{ helper_node_info.query_result }}"
  loop_control:
    loop_var: node_info
  when:
    - helper_node_info.query_result is defined
    - helper_node_info.query_result | length > 0
