# Copyright 2024 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

# Usage: initiate_telemetry.yml
python_version: "{{ ansible_python_interpreter }}"
mysqldb_name: "idrac_telemetrydb"
timescaledb_name: "telemetry_metrics"
telemetry_report_path: "/opt/omnia/telemetry/idrac_telemetry_report.yml"
idrac_telemetry_container: "idrac_telemetry_receiver"
# report_template_path: "/opt/omnia/telemetry/templates/telemetry_report.j2"
mysqldb_insert_fail_msg: "Failed to add/get iDRAC credential details in the mysql database.
 This could be due to the tables in the mysqldb not being accessible at the moment. Please try running the playbook again after some time."
db_retries: 10
db_delay: 10
mysqldb_container_port: 3306
filemode: "0644"
mysqldb_host: "127.0.0.1"
telemetry_report: |
  ===== Telemetry playbook execution Summary =====

  Total IPs Found: {{ idrac_ip_count }}
  IPs List:
    {% for item in idrac_ip %}
    - {{ item }}
    {% endfor %}

  IP with Telemetry not supported: {{ failed_idrac_count }}
  IPs List (Telemetry not supported):
    {% for item in failed_idrac %}
    - {{ item }}
    {% endfor %}

  IPs with Telemetry Initiated: {{ filtered_idrac_count }}
  IPs List (Telemetry Activated):
    {% for item in telemetry_idrac %}
    - {{ item }}
    {% endfor %}

  Check the report file at {{ telemetry_report_path }} for all Telemetry Activated IPs.

  =====================================

# Usage: add_host_goups.yml
bmc_group_data_filename: "/opt/omnia/telemetry/bmc_group_data.csv"
service_node_metadata_path: "/opt/omnia/telemetry/bmc_group_data.csv"
