# Copyright 2024 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

---
kube_version: "{{ hostvars['localhost']['kubespray_version'] }}"
k8s_compatible_tag: "{{ hostvars['localhost']['k8s_to_kubespray_comp_ver']['compatible_tags'].keys() | list }}"
k8s_version: "{{ hostvars['localhost']['k8s_version'] }}"
supported_k8s_version:
  "v2.26.0": [v1.30.4, v1.30.3, v1.30.2, v1.30.1, v1.30.0, v1.29.7, v1.29.6, v1.29.5, v1.29.4, v1.29.3, v1.29.2, v1.29.1, v1.29.0, v1.28.12, v1.28.11, v1.28.10, v1.28.9, v1.28.8, v1.28.7, v1.28.6, v1.28.5, v1.28.4, v1.28.3, v1.28.2, v1.28.1, v1.28.0] # noqa: yaml[line-length]
  "v2.27.0": [v1.31.4, v1.31.3, v1.31.2, v1.31.1, v1.31.0, v1.30.8, v1.30.7, v1.30.6, v1.30.5, v1.30.4, v1.30.3, v1.30.2, v1.30.1, v1.30.0, v1.29.12, v1.29.11, v1.29.10, v1.29.9, v1.29.8, v1.29.7, v1.29.6, v1.29.5, v1.29.4, v1.29.3, v1.29.2, v1.29.1, v1.29.0] # noqa: yaml[line-length]
  "v2.28.0": [1.32.5, 1.32.4, 1.32.2, 1.32.3, 1.32.1, 1.32.0, 1.31.9, 1.31.8, 1.31.7, 1.31.6, 1.31.5, 1.31.4, 1.31.3, 1.31.2, 1.31.1, 1.31.0, 1.30.13, 1.30.12, 1.30.11, 1.30.10, 1.30.9, 1.30.8, 1.30.7, 1.30.6, 1.30.5, 1.30.4, 1.30.3, 1.30.2, 1.30.1, 1.30.0] # noqa: yaml[line-length]
omnia_kubespray_latest_ver_msg: "Latest omnia_kubespray tag is: {{ kubespray_latest_tag.split(':')[1]  }}"
k8s_compatibility_message: "k8s {{ k8s_compatible_tag }} is compatible with existing {{ kube_version }}"