# Copyright 2024 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

# - name: Update Inventory with ansible_host information
#   ansible.builtin.import_playbook: ../utils/servicetag_host_mapping.yml
#   when: not ( hostvars['127.0.0.1']['update_inventory_executed'] | default(false) | bool )

# - name: Check if package manager is not locked
#   ansible.builtin.import_playbook: ../utils/check_package_lock.yml
#   when: not ( hostvars['127.0.0.1']['apt_lock_status'] | default(false) | bool )

- name: Set_fact for fetch omnia config credentials
  hosts: localhost
  connection: local
  tasks:
    - name: Set dynamic run tags including 'telemetry'
      ansible.builtin.set_fact:
        omnia_run_tags: "{{ (ansible_run_tags | default([]) + ['telemetry']) | unique }}"
        cacheable: true

- name: Invoke get_config_credentials.yml
  ansible.builtin.import_playbook: ../utils/credential_utility/get_config_credentials.yml

- name: Include input project directory
  when: not project_dir_status | default(false) | bool
  ansible.builtin.import_playbook: ../utils/include_input_dir.yml

- name: Create provision container group
  ansible.builtin.import_playbook: ../utils/create_container_group.yml
  vars:
    oim_group: true

- name: Validate containers are running
  hosts: oim
  connection: ssh
  tasks:
    - name: Validate telemetry container is running
      ansible.builtin.include_role:
        name: telemetry_validation
        tasks_from: validate_telemetry_container.yml

- name: Validate telemetry input parameters
  hosts: localhost
  connection: local
  any_errors_fatal: true
  tasks:
    - name: Validate telemetry input parameters
      ansible.builtin.include_role:
        name: telemetry_validation
        tasks_from: validation_status_check.yml

# - name: Update Repositories/Registries on nodes
#   ansible.builtin.import_playbook: ../utils/update_user_repo.yml
#   when: not ( hostvars['127.0.0.1']['update_user_repo_executed'] | default(false) | bool )

- name: Telemetry for omnia
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - idrac_telemetry
