# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

---

- name: Include metadata vars
  ansible.builtin.include_vars: "{{ omnia_metadata_file }}"
  register: include_metadata
  no_log: true

- name: Initialize SELinux policy
  ansible.builtin.set_fact:
    selinux_option: ":z"

- name: Set SELinux policy
  ansible.builtin.set_fact:
    selinux_option: ""
  when:
    - omnia_share_option == 'NFS'
    - nfs_type == 'external'

- name: Get oim node name
  ansible.builtin.command: hostname -s
  register: oim_node_name
  changed_when: false

- name: Set facts
  ansible.builtin.set_fact:
    admin_nic: "{{ hostvars['localhost']['admin_nic'] }}"
    admin_nic_ip: "{{ hostvars['localhost']['admin_nic_ip'] }}"
    admin_nic_forwarders: "{{ hostvars['localhost'].network_data.admin_network.DNS | default('', true) }}"
    oim_node_name: "{{ oim_node_name.stdout }}"
    admin_net_addr: "{{ hostvars['localhost']['admin_net_addr'] }}"
    admin_netmask_bits: "{{ hostvars['localhost']['admin_netmask_bits'] }}"
    docker_username: "{{ hostvars['localhost']['docker_username'] }}"
    docker_password: "{{ hostvars['localhost']['docker_password'] }}"
  no_log: true

- name: Export firewall ports for pcs container
  ansible.builtin.include_tasks: firewall_settings.yml

- name: Run podman login command
  ansible.builtin.include_tasks: podman_login.yml
  when: docker_username | length > 1 and docker_password | length > 1
