#  Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---

# Usage: mysqldb_deployment.yml
mysqldb_storage: 1Gi
mysqldb_pvc_name: mysqldb-storage-claim
mysqldb_k8s_name: mysqldb
statefulset_replicas: 1
mysqldb_container_port1: 3306
mysqldb_container_port2: 33060

# Usage: k8s_secrets.yml
mysqldb_secrets_name: mysqldb-credentials
