# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

# Usage: deploy_loki_container.yml
omnia_nfs_share: "{{ oim_shared_path }}/omnia"
promtail_container_name: "promtail"
promtail_image: grafana/promtail
promtail_image_tag: "3.4.1"
dir_permissions_755: "0755"
loki_container_name: "loki"
loki_image: grafana/loki 
loki_image_tag: "3.4.1"

loki_log_directory: "{{ omnia_nfs_share }}/log/loki"
loki_data_directory: "{{ omnia_nfs_share }}/telemetry/loki"
loki_podman_volumes:
  - { name: "loki_log", path: "{{ loki_log_directory }}" }
  - { name: "loki_data", path: "{{ loki_data_directory }}" }
loki_volumes:
  - "loki_log:/var/log/loki{{ selinux_option }}"
  - "loki_data:/var/lib/loki{{ selinux_option }}"

loki_config_url: "https://raw.githubusercontent.com/grafana/loki/v{{ loki_image_tag }}/cmd/loki/loki-local-config.yaml" 
promtail_config_url: "https://raw.githubusercontent.com/grafana/loki/v{{ promtail_image_tag }}/clients/cmd/promtail/promtail-docker-config.yaml"
loki_config_file: "{{ loki_data_directory}}/loki-config.yaml"
promtail_config_file: "{{ loki_data_directory}}/promtail-config.yaml"



promtail_container_success_msg: "Promtail container is deployed and running successfully."
promtail_container_failure_msg: "Promtail container deployment failed."
promtail_image_pull_fail_msg: "Failed to pull Promtail image."
promtail_image_not_found_msg: "Promtail image not found after pull."





loki_container_success_msg: "Loki container is deployed and running successfully."
container_failure_msg: "Loki or Promtail container deployment failed."
loki_image_pull_fail_msg: "Failed to pull Loki image."
loki_image_not_found_msg: "Loki image not found after pull."