# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

omnia_nfs_share: "{{ oim_shared_path }}/omnia"
dir_mode: "0755"
file_mode: "0644"
telemetry_dir_path: "{{ omnia_nfs_share }}/telemetry"
idrac_telemetry_reference_path: "{{ idrac_telemetry_receiver_dir_path }}/iDRAC-Telemetry-Reference-Tools"
max_retries: 10
delay_count: 5

# Usage: deploy_prometheus_pump_container.yml
prometheus_pump_logs_dir: "{{ omnia_nfs_share }}/log/telemetry/prometheus_pump"
prometheus_pump_dir: "{{ telemetry_dir_path }}/prometheus_pump"
prometheus_pump_directories:
 - { path: "{{ prometheus_pump_logs_dir }}", mode: "0755" }
 - { path: "{{ prometheus_pump_dir }}", mode: "0755" }
prometheus_pump_volumes:
 - "{{ idrac_telemetry_reference_path }}:/go/src/github.com/telemetry-reference-tools{{ selinux_option }}"
prometheus_pump_container_name: "prometheus_pump"
prometheus_pump_image: "docker.io/library/golang:1.17"
prometheus_pump_receiver_env:
 MESSAGEBUS_HOST: "localhost"
 MESSAGEBUS_PORT: "61613"
 PROMETHEUSDB_SERVER: "prometheus"
prometheus_pump_container_success_msg: "The {{ prometheus_pump_container_name }} container has been successfully deployed."
prometheus_pump_container_failure_msg: |
  Deployment of {{ prometheus_pump_container_name }} container failed.
  To resolve this, check logs using 'podman logs {{ prometheus_pump_container_name }}' from OIM
  and then run utility/oim_cleanup.yml playbook to clean up existing OIM resources.
  After cleanup, re-run the prepare_oim.yml playbook to successfully deploy the {{ prometheus_pump_container_name }} container.

# Usage: deploy_prometheus_container.yml
prometheus_logs_dir: "{{ omnia_nfs_share }}/log/telemetry/prometheus"
prometheus_data_dir: "{{ telemetry_dir_path }}/prometheus/prometheus_data"
prometheus_dir: "{{ telemetry_dir_path }}/prometheus"
proemetheus_yml_temp_src: "{{ role_path }}/templates/prometheus_yml.j2"
prometheus_podman_volumes:
 - { name: "prometheus_data", path: "{{ prometheus_data_dir }}" }
 - { name: "prometheus_log", path: "{{ prometheus_logs_dir }}" }
prometheus_container_name: "prometheus"
prometheus_image: "prom/prometheus:v2.36.0"
prometheus_volumes:
 - "{{ prometheus_dir }}/prometheus.yml:/config/prometheus.yml:ro,Z"
 - "prometheus_data:/prometheus"
 - "prometheus_log:/prometheus/log"

prometheus_env:
 PROMETHEUS_DB: "poweredge_telemetry_metrics"
 node.name: "127.0.0.1"
prometheus_container_success_msg: "The {{ prometheus_container_name }} container has been successfully deployed."
prometheus_container_failure_msg: |
  Deployment of {{ prometheus_container_name }} container failed.
  To resolve this, check logs using 'podman logs {{ prometheus_container_name }}' from OIM
  and then run utility/oim_cleanup.yml playbook to clean up existing OIM resources.
  After cleanup, re-run the prepare_oim.yml playbook to successfully deploy the {{ prometheus_container_name }} container.
