# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

# Usage: configure_passive_servicenode_config.yml
pcs_group: "omnia"
monitor_interval_30s: "30s"
timeout_60s: "60s"
sn_ha_migration_threshold: 3
service_node_base_dir: "/opt/omnia/service_nodes"
file_permissions: '0755'
failure_timeout: '100s'

# Usage: main.yml
service_ha_config_json: "/opt/omnia/service_nodes/service_ha_config_data.json"
high_availability_config_path: "{{ hostvars['localhost']['input_project_dir'] }}/high_availability_config.yml"
