---
- name: Check that the local_repo_config.yml exists
  ansible.builtin.stat:
    path: "{{ local_repo_config_file }}"
  register: stat_result

- name: Fail if local_repo_config.yml file doesn't exist
  ansible.builtin.fail:
    msg: "{{ fail_msg_local_repo_config_file }}"
  when: not stat_result.stat.exists

- name: Include variable file local_repo_config.yml
  block:
    - name: Include variable file local_repo_config.yml
      ansible.builtin.include_vars: "{{ local_repo_config_file }}"
      register: include_local_repo_config
      no_log: true
  rescue:
    - name: Failed to include local_repo_config.yml
      ansible.builtin.fail:
        msg: "{{ local_repo_config_syntax_fail_msg }} Possible Syntax Error Hints: {{ include_local_repo_config.message }}"
