# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---

# Usage: rename_service_node_nic.yml, set_service_node_details.yml
xcat_bin_path: "/opt/xcat/bin"
xcat_sbin_path: "/opt/xcat/sbin"
dhcp_config_fail_msg: "Failed. makedhcp -n command is not successful. Error:"

# Usage: set_service_node_details.yml
hosts_entry_warning_msg: "[WARNING] makehosts command is not successful. Error:"
dhcp_config_apply_fail_msg: "Failed. makedhcp -a command is not successful. Error:"
dns_config_warning_msg: "[WARNING] makedns -n command is not successful. Error:"
service_retries: 3
xcatd_service: "xcatd.service"
xcat_start_fail_msg: "Failed to start xcatd services on {{ hostvars[inventory_hostname]['service_tag'] }}"

# Usage: copy_syncfiles.yml
syncfiles_mode: "0755"
service_node_sync_files:
  - { src: "{{ hostvars['omnia_provision']['syncfiles_share_path'] }}", dest: "{{ hostvars['omnia_provision']['provision_shared_path'] }}" }
  - { src: "/opt/omnia/provision/install", dest: "/", rsync_opts: ["--exclude=autoinst"] }
  - { src: "/opt/omnia/provision/tftpboot", dest: "/" }
