# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: Check if Promtail container is present
  containers.podman.podman_container_info:
    name: "{{ promtail_container_name }}"
  register: promtail_container_info
  failed_when: false

- name: Deploy Promtail container and check deployment status
  when:
    - promtail_container_info.containers | length == 0 or promtail_container_info.containers[0].State.Status != 'running'
  block:
    - name: Pull Promtail Podman image
      containers.podman.podman_image:
        name: "{{ promtail_image }}"
        tag: "{{ promtail_image_tag }}"
        state: present
      register: image_pull_result

    - name: Fail if Promtail image pull fails
      ansible.builtin.fail:
        msg: "{{ promtail_image_pull_fail_msg }}"
      when: image_pull_result.failed

    - name: Verify Promtail image exists
      containers.podman.podman_image_info:
        name: "{{ promtail_image }}:{{ promtail_image_tag }}"
      register: image_facts

    - name: Fail if Promtail image not found
      ansible.builtin.fail:
        msg: "{{ promtail_image_not_found_msg.splitlines() | join(' ') }}"
      when: not image_facts.images

    - name: Deploy Promtail container
      containers.podman.podman_container:
        name: "{{ promtail_container_name }}"
        image: "{{ promtail_image }}:{{ promtail_image_tag }}"
        state: started
        recreate: false
        restart_policy: "no"
        network_mode: host
        volumes: "{{ promtail_volumes }}"
        etc_hosts:
          loki: "127.0.0.1"
          promtail: "127.0.0.1"
        command:
          - "-config.file={{ container_config_mnt }}/promtail-config.yaml"

    - name: Check if Promtail container is running after deployment
      containers.podman.podman_container_info:
        name: "{{ promtail_container_name }}"
      register: promtail_container_status
      until: promtail_container_status.containers | length > 0 and
             promtail_container_status.containers[0].State.Status == 'running'
      retries: "{{ max_retries }}"
      delay: "{{ delay_count }}"

    - name: Notify user of Promtail deployment status
      ansible.builtin.debug:
        msg: "{{ promtail_container_success_msg.splitlines() | join(' ') }}"
      when:
        - promtail_container_status.containers | length > 0
        - promtail_container_status.containers[0].State.Status == 'running'

  rescue:
    - name: Promtail container deployment failed
      ansible.builtin.fail:
        msg: "{{ promtail_container_failure_msg.splitlines() | join(' ') }}"
