- name: Check if Promtail container is present # noqa: name[template]
  containers.podman.podman_container_info:
    name: "{{ promtail_container_name }}"
  register: promtail_container_info
  failed_when: false

- name: Deploy Promtail container and check deployment status
  when:
    - promtail_container_info.containers | length == 0 or promtail_container_info.containers[0].State.Status != 'running'
  block:
    - name: Create Promtail log directory
      ansible.builtin.file:
        path: "{{ promtail_log_dir }}"
        state: directory
        mode: "{{ dir_permissions_755 }}"

    - name: Create Podman bind-mounted volumes for Loki
      containers.podman.podman_volume:
        name: "{{ item.name }}"
        state: present
        driver: local
        options:
          - "o=bind"
          - "type=none"
          - "device={{ item.path }}"
      loop: "{{ promtail_podman_volume }}"

    - name: Copy Promtail config file 
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "{{ item.mode }}"
      loop: "{{ promtail_config_file_path }}"

    - name: Pull Promtail Podman image
      containers.podman.podman_image:
        name: "{{ promtail_image }}"
        tag: "{{ promtail_image_tag }}"
        state: present
      register: image_pull_result

    - name: Fail if Promtail image pull fails
      ansible.builtin.fail:
        msg: "{{ promtail_image_pull_fail_msg }}"
      when: image_pull_result.failed

    - name: Verify Promtail image exists
      containers.podman.podman_image_info:
        name: "{{ promtail_image }}:{{ promtail_image_tag }}"
      register: image_facts

    - name: Fail if Promtail image not found
      ansible.builtin.fail:
        msg: "{{ promtail_image_not_found_msg.splitlines() | join(' ') }}"
      when: not image_facts.images

    - name: Deploy Promtail container
      containers.podman.podman_container:
        name: "{{ promtail_container_name }}"
        image: "{{ promtail_image }}:{{ promtail_image_tag }}"
        state: started
        recreate: false
        restart_policy: "no"
        network_mode: host
        volumes: "{{ promtail_volumes }}"
        etc_hosts:
          loki: "127.0.0.1"
          promtail: "127.0.0.1"
        command:
          - "-config.file={{ container_config_mnt }}/promtail-config.yaml"

    - name: Check if Promtail container is running after deployment
      containers.podman.podman_container_info:
        name: "{{ promtail_container_name }}"
      register: promtail_container_status
      until: promtail_container_status.containers | length > 0 and
             promtail_container_status.containers[0].State.Status == 'running'
      retries: "{{ max_retries }}"
      delay: "{{ delay_count }}"

    - name: Notify user of Promtail deployment status
      ansible.builtin.debug:
        msg: "{{ promtail_container_success_msg.splitlines() | join(' ') }}"
      when:
        - promtail_container_status.containers | length > 0
        - promtail_container_status.containers[0].State.Status == 'running'

  rescue:
    - name: Promtail container deployment failed
      ansible.builtin.fail:
        msg: "{{ promtail_container_failure_msg.splitlines() | join(' ') }}"