#  Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---

# Usage: deploy_nvidia_device_plugin.yml
k8s_tmp_dir: "/root/k8s"
nvidia_runtime_source: "nvidia_runtime_class.yml"
nvidia_runtime_dest: "{{ k8s_tmp_dir }}/nvidia-runtime_class.yml"
nvidia_device_plugin_repo: "{{ hostvars['localhost']['offline_tarball_path'] }}/nvidia-device-plugin/nvidia-device-plugin.tar.gz"
nvidia_device_plugin_dest_repo: "{{ k8s_tmp_dir }}/nvidia-device-plugin.tar.gz"
mig_strategy: none
gpu_discovery_feature: true
file_mode: "0644"
ansible_python_interpreter: /usr/bin/python3.11

# Usage: deploy_nvidia_gpu_operator.yml
nvidia_gpu_operator_path: "{{ k8s_tmp_dir }}/nvidia-gpu-operator-v{{ hostvars['localhost']['nvidia_gpu_operator_version'] }}"
nvidia_gpu_operator_config_file_path: "{{ nvidia_gpu_operator_path }}/gpu_operator_config.yml"
nvidia_gpu_operator_helm_chart: "nvidia-gpu-operator-v{{ hostvars['localhost']['nvidia_gpu_operator_version'] }}.tar.gz"
nvidia_gpu_operator_helm_chart_path: "/tmp/{{ nvidia_gpu_operator_helm_chart }}"
fail_msg_nvidia_gpu_operator_helm_chart_download: "Failed to get nvidia gpu operator helm chart from local repo location: {{ offline_tarball_path }}"
permission_644: "0644"
owner_value: "root"
group_value: "root"
gpu_operators_namespace: "gpu-operator"
timeout_min_sec: 600s
directory_permissions: "0755"
