name: Pylint

on:
  pull_request:
    branches:
      - staging
      - pub/new_architecture
      - pub/telemetry
      - pub/composable_software_roles
      - pub/local_repo

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    env:
      PYLINT_THRESHOLD: 8
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ansible pylint kubernetes prettytable requests

    - name: Get changed Python files (excluding deleted)
      id: changed-files
      run: |
        git fetch origin ${{ github.base_ref }}
        # Get changed *.py files between base and HEAD
        CHANGED=$(git diff --diff-filter=d --name-only origin/${{ github.base_ref }} HEAD -- '*.py' || true)
        if [ -z "$CHANGED" ]; then
          echo "files="
        else
          # Filter only existing files (just in case)
          FILES=""
          for f in $CHANGED; do
            if [ -f "$f" ]; then
              FILES="$FILES $f"
            fi
          done
          # Trim leading whitespace
          FILES="${FILES#"${FILES%%[![:space:]]*}"}"
          echo "files=$FILES"
          echo "files=$FILES" >> "$GITHUB_OUTPUT"
        fi

    - name: Run pylint on changed files
      if: steps.changed-files.outputs.files != ''
      run: |
        echo "Running pylint on: ${{ steps.changed-files.outputs.files }}"
        pylint ${{ steps.changed-files.outputs.files }} --fail-under=${PYLINT_THRESHOLD}
