name: Pylint

on:
  push:
    branches:
      - main
      - staging
      - pub/new_architecture
      - pub/telemetry

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    env:
      PYLINT_THRESHOLD: 8  # 👈 Set your desired threshold here
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')  --fail-under=${PYLINT_THRESHOLD}
